#! /bin/sh

sxhkd &

xrdb -load ~/.Xresources &
xsetroot -cursor_name left_ptr &
start-pulseaudio-x11 &
#feh --bg-fill /home/gracz/Pictures/Wallpapers/mike-kononov-lFv0V3_2H6s-unsplash.jpg &
feh --bg-fill /home/gracz/Pictures/Wallpapers/spirited_crow.jpg &
~/.config/polybar/launch.sh &
~/.config/compton.sh &
dunst &
pgrep -x discord || discord &
#pgrep -x spotify || spotify &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop=^6
bspc rule -a spotify desktop=^7

