#! /bin/sh

pgrep -x sxhkd || sxhkd &

xrdb -load ~/.Xresources &
xsetroot -cursor_name left_ptr &
pipewire &
feh --bg-fill --no-fehbg $HOME/pics/wall/wall &
#~/.config/polybar/launch.sh &
pgrep -x polybar || $HOME/.config/polybar/launch.sh &
$HOME/.config/compton.sh &
dunst &
pgrep -x Discord || Discord &
#pgrep -x spotify || spotify &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop=^6
bspc rule -a spotify desktop=^7

